### ISSUE TITLE
sbcl 2.3.7 not build on arm64

### ISSUE THREAD

**Issue by diasbruno** [fukamachi/dockerfiles#79]
sbcl version below 2.3.7 where both build for amd64 and arm64,
but 2.3.7 is not.

I couldn't find anything on the commits that could cause the problem,
so I believe it was build manually.

**Comment by fukamachi** [comment]
Hi, thanks for reporting.

As you noticed, building ARM64 images isn’t automated because GitHub Actions doesn't have the architecture support. They had been pushed by hand on my machine.
But, I’m in a hospital for weeks, so I can’t access a machine to build it.

I’ll do it when I get back home.

fukamachi
2023年8月3日 11:44 +0900、Bruno Dias ***@***.***>のメール:

**Comment by diasbruno** [comment]
That's fine. I set to version 2.3.6, maybe later I build my own or let me know how can I help.

Hope everything is fine. Take care, bro.

**Comment by fukamachi** [comment]
Built and pushed!

I left a note to build them on ARM64 machine for the future:

```shell
$ ./build.sh sbcl 2.3.7 debian
$ ./build.sh sbcl 2.3.7 ubuntu
$ ./docker-release-amend.sh fukamachi/sbcl:2.3.7-debian fukamachi/sbcl:2.3.7 fukamachi/sbcl:latest-debian fukamachi/sbcl:latest
$ ./docker-release-amend.sh fukamachi/sbcl:2.3.7-ubuntu fukamachi/sbcl:latest-ubuntu
```
